// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_log.h"
#include "esp_err.h"

#define MODE_SPO2 1
#define MODE_HR 2

#define MLX90614_DEFAULT_ADDRESS 0x5A // default chip address(slave address) of MLX90614
#define MLX90614_SDA_GPIO 27          // sda for MLX90614
#define MLX90614_SCL_GPIO 26          // scl for MLX90614
#define MLX90614_VCC_GPIO 0           // vcc for MLX90614
///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t *e);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Container1;
void ui_event_Button4(lv_event_t *e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Container2;
void ui_event_Button1(lv_event_t *e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Container3;
void ui_event_Button2(lv_event_t *e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Container4;
void ui_event_Button5(lv_event_t *e);
lv_obj_t *ui_Button5;
lv_obj_t *ui_Label19;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t *e);
lv_obj_t *ui_Screen2;
void ui_event_Button3(lv_event_t *e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label16;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT)
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}
// 测量心率
void ui_event_Button4(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        // 测量
        // 定义长度为2的字符串
        char HR_result_str[3];
        Mode_Change(MODE_HR);
        Para_GET();
        // 将 int 类型的值转换为字符串
        sprintf(HR_result_str, "%02d", get_bpm());
        _ui_label_set_property(ui_Label4, _UI_LABEL_PROPERTY_TEXT, HR_result_str);
    }
}
// 测量血氧
void ui_event_Button1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        // 测量
        // 定义长度为5的字符串用来显示
        char spo2_result_str[5];
        Mode_Change(MODE_SPO2);
        Para_GET();
        // 将 double 类型的值转换为字符串
        sprintf(spo2_result_str, "%.2f", get_spo2());
        _ui_label_set_property(ui_Label7, _UI_LABEL_PROPERTY_TEXT, spo2_result_str);
    }
}
// 测量体温
void ui_event_Button2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        // 定义长度为4的字符串存放结果
        char body_temp[4];
        float to = 0; // temperature of object
        // 测量
        MLX90614_GetTo(MLX90614_DEFAULT_ADDRESS, &to);
        printf("forehead temperature:%lf \r\n", to);
        sprintf(body_temp, "%.1f", to);
        _ui_label_set_property(ui_Label11, _UI_LABEL_PROPERTY_TEXT, body_temp);
    }
}
// 测量环境温湿度
void ui_event_Button5(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        // 测量
        xTaskCreate(&DHT11_Task, "DHT11_Task", 8192, NULL, 3, NULL);
        // 设置环境温度
        //_ui_label_set_property(ui_Label12, _UI_LABEL_PROPERTY_TEXT, envir_temp);
        // 设置环境湿度
        //_ui_label_set_property(ui_Label13, _UI_LABEL_PROPERTY_TEXT, envir_humid);
    }
}
void ui_event_Screen2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT)
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////
void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
